-- Align the Hermes-rebuilt schema with the deep player statistics already
-- exposed by SofaScore's /event/{id}/lineups payload and mapped in
-- backfill_runner.py. Existing Stage 2 rows are preserved.
--
-- The production migration was applied on 2026-09-01. This file is the
-- reproducible record for a newly rebuilt appdb schema.

ALTER TABLE match_player_stats
  ADD COLUMN total_pass DECIMAL(14,4) NULL,
  ADD COLUMN accurate_pass DECIMAL(14,4) NULL,
  ADD COLUMN total_long_balls DECIMAL(14,4) NULL,
  ADD COLUMN accurate_long_balls DECIMAL(14,4) NULL,
  ADD COLUMN total_own_half_passes DECIMAL(14,4) NULL,
  ADD COLUMN accurate_own_half_passes DECIMAL(14,4) NULL,
  ADD COLUMN total_opposition_half_passes DECIMAL(14,4) NULL,
  ADD COLUMN accurate_opposition_half_passes DECIMAL(14,4) NULL,
  ADD COLUMN total_cross DECIMAL(14,4) NULL,
  ADD COLUMN accurate_cross DECIMAL(14,4) NULL,
  ADD COLUMN key_pass DECIMAL(14,4) NULL,
  ADD COLUMN goal_assist DECIMAL(14,4) NULL,
  ADD COLUMN big_chance_created DECIMAL(14,4) NULL,
  ADD COLUMN total_shots DECIMAL(14,4) NULL,
  ADD COLUMN on_target_scoring_attempt DECIMAL(14,4) NULL,
  ADD COLUMN shot_off_target DECIMAL(14,4) NULL,
  ADD COLUMN blocked_scoring_attempt DECIMAL(14,4) NULL,
  ADD COLUMN expected_goals DECIMAL(14,4) NULL,
  ADD COLUMN expected_goals_on_target DECIMAL(14,4) NULL,
  ADD COLUMN expected_assists DECIMAL(14,4) NULL,
  ADD COLUMN big_chance_missed DECIMAL(14,4) NULL,
  ADD COLUMN shot_value_normalized DECIMAL(14,4) NULL,
  ADD COLUMN duel_lost DECIMAL(14,4) NULL,
  ADD COLUMN aerial_won DECIMAL(14,4) NULL,
  ADD COLUMN aerial_lost DECIMAL(14,4) NULL,
  ADD COLUMN total_contest DECIMAL(14,4) NULL,
  ADD COLUMN won_contest DECIMAL(14,4) NULL,
  ADD COLUMN challenge_lost DECIMAL(14,4) NULL,
  ADD COLUMN total_tackle DECIMAL(14,4) NULL,
  ADD COLUMN won_tackle DECIMAL(14,4) NULL,
  ADD COLUMN interception_won DECIMAL(14,4) NULL,
  ADD COLUMN total_clearance DECIMAL(14,4) NULL,
  ADD COLUMN ball_recovery DECIMAL(14,4) NULL,
  ADD COLUMN outfielder_block DECIMAL(14,4) NULL,
  ADD COLUMN last_man_tackle DECIMAL(14,4) NULL,
  ADD COLUMN error_lead_to_a_goal DECIMAL(14,4) NULL,
  ADD COLUMN error_lead_to_a_shot DECIMAL(14,4) NULL,
  ADD COLUMN dribble_value_normalized DECIMAL(14,4) NULL,
  ADD COLUMN dispossessed DECIMAL(14,4) NULL,
  ADD COLUMN unsuccessful_touch DECIMAL(14,4) NULL,
  ADD COLUMN fouls DECIMAL(14,4) NULL,
  ADD COLUMN was_fouled DECIMAL(14,4) NULL,
  ADD COLUMN total_offside DECIMAL(14,4) NULL,
  ADD COLUMN own_goals DECIMAL(14,4) NULL,
  ADD COLUMN saves DECIMAL(14,4) NULL,
  ADD COLUMN saved_shots_from_inside_the_box DECIMAL(14,4) NULL,
  ADD COLUMN good_high_claim DECIMAL(14,4) NULL,
  ADD COLUMN total_keeper_sweeper DECIMAL(14,4) NULL,
  ADD COLUMN accurate_keeper_sweeper DECIMAL(14,4) NULL,
  ADD COLUMN goals_prevented DECIMAL(14,4) NULL,
  ADD COLUMN keeper_save_value DECIMAL(14,4) NULL,
  ADD COLUMN goalkeeper_value_normalized DECIMAL(14,4) NULL,
  ADD COLUMN top_speed DECIMAL(14,4) NULL,
  ADD COLUMN kilometers_covered DECIMAL(14,4) NULL,
  ADD COLUMN number_of_sprints DECIMAL(14,4) NULL,
  ADD COLUMN meters_covered_running_km DECIMAL(14,4) NULL,
  ADD COLUMN meters_covered_high_speed_running_km DECIMAL(14,4) NULL,
  ADD COLUMN meters_covered_sprinting_km DECIMAL(14,4) NULL,
  ADD COLUMN total_ball_carries_distance DECIMAL(14,4) NULL,
  ADD COLUMN ball_carries_count DECIMAL(14,4) NULL,
  ADD COLUMN total_progression DECIMAL(14,4) NULL,
  ADD COLUMN progressive_ball_carries_count DECIMAL(14,4) NULL,
  ADD COLUMN total_progressive_ball_carries_distance DECIMAL(14,4) NULL,
  ADD COLUMN best_ball_carry_progression DECIMAL(14,4) NULL,
  ADD COLUMN touches DECIMAL(14,4) NULL,
  ADD COLUMN possession_lost_ctrl DECIMAL(14,4) NULL,
  ADD COLUMN pass_value_normalized DECIMAL(14,4) NULL,
  ADD COLUMN defensive_value_normalized DECIMAL(14,4) NULL,
  ADD COLUMN statistics_type VARCHAR(50) NULL,
  ADD COLUMN rating_versions JSON NULL,
  ADD COLUMN raw_statistics JSON NULL;
